2019-04-28 17:22:34,440 check_dns.py[line:117] INFO named process is not existed,try restart;
